services:
  gdrive-mcp:
    build: .
    container_name: gdrive-mcp-server
    volumes:
      - ./credentials:/credentials:ro
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_URL=redis://redis:6379
      - GDRIVE_CREDENTIALS_PATH=/credentials/.gdrive-server-credentials.json
      - GDRIVE_OAUTH_PATH=/credentials/gcp-oauth.keys.json
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - mcp-network

  gdrive-mcp-auth:
    build: .
    container_name: gdrive-mcp-auth
    volumes:
      - ./credentials:/credentials
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - GDRIVE_CREDENTIALS_PATH=/credentials/.gdrive-server-credentials.json
      - GDRIVE_OAUTH_PATH=/credentials/gcp-oauth.keys.json
    network_mode: host
    stdin_open: true
    tty: true
    profiles:
      - auth

  redis:
    image: redis:7-alpine
    container_name: gdrive-mcp-redis
    volumes:
      - redis_data:/data
    networks:
      - mcp-network

volumes:
  redis_data:

networks:
  mcp-network:
    driver: bridge