services:
  gdrive-mcp:
    build: .
    container_name: gdrive-mcp-server
    volumes:
      - ./credentials:/credentials:ro
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=silent
      - REDIS_URL=redis://redis:6379
      - GDRIVE_OAUTH_PATH=/credentials/gcp-oauth.keys.json
      - GDRIVE_TOKEN_STORAGE_PATH=/credentials/.gdrive-mcp-tokens.json
      - GDRIVE_TOKEN_AUDIT_LOG_PATH=/app/logs/gdrive-mcp-audit.log
      - GDRIVE_TOKEN_ENCRYPTION_KEY=${GDRIVE_TOKEN_ENCRYPTION_KEY}
      - GDRIVE_TOKEN_REFRESH_INTERVAL=1800000
      - GDRIVE_TOKEN_PREEMPTIVE_REFRESH=600000
      - GDRIVE_TOKEN_MAX_RETRIES=3
      - GDRIVE_TOKEN_RETRY_DELAY=1000
      - GDRIVE_TOKEN_HEALTH_CHECK=true
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - redis
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "node", "dist/index.js", "health"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s

  # Authentication service (kept for reference but not used)
  # Authentication should be done on the host using ./scripts/auth.sh
  # gdrive-mcp-auth:
  #   build: .
  #   container_name: gdrive-mcp-auth
  #   volumes:
  #     - ./credentials:/credentials
  #     - ./data:/data
  #     - ./logs:/app/logs
  #   environment:
  #     - NODE_ENV=development
  #     - LOG_LEVEL=info
  #     - GDRIVE_CREDENTIALS_PATH=/credentials/.gdrive-server-credentials.json
  #     - GDRIVE_OAUTH_PATH=/credentials/gcp-oauth.keys.json
  #     - GDRIVE_TOKEN_STORAGE_PATH=/credentials/.gdrive-mcp-tokens.json
  #     - GDRIVE_TOKEN_AUDIT_LOG_PATH=/app/logs/gdrive-mcp-audit.log
  #     - GDRIVE_TOKEN_ENCRYPTION_KEY=${GDRIVE_TOKEN_ENCRYPTION_KEY}
  #   network_mode: host
  #   stdin_open: true
  #   tty: true
  #   profiles:
  #     - auth

  redis:
    image: redis:7-alpine
    container_name: gdrive-mcp-redis
    volumes:
      - redis_data:/data
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  redis_data:

networks:
  mcp-network:
    driver: bridge